config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/profil', to: 'users#edit', as: :edit_profil
  patch '/profil', to: 'users#update', as: :profil

  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create', as: :sessions
  delete '/logout', to: 'sessions#destroy', as: :session

  resources :passwords, only: [:new, :create, :edit, :update]

  resources :users, only: [:new, :create] do
    member do
      get 'confirm'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :avatar_file

  has_secure_password
  has_secure_token :confirmation_token
  has_secure_token :recover_password

  after_save :avatar_upload

  after_destroy_commit :avatar_destroy

  validates :username, format: { with: /\A[a-zA-Z0-9_]{2,20}\z/, message: "ne doit contenir que des caractères alpha numériques ou des underscore" }, uniqueness: { case_sensitive: false }
  validates :email, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }, uniqueness: { case_sensitive: false }
  validates :avatar_file, file: { ext: [:jpg, :png] }

  def to_session
    { id: id }
  end

  def avatar_url
    '/' + [self.class.name.downcase.pluralize, id.to_s, 'avatar.jpg'].join('/')
  end

  private

  def avatar_upload
    base_path = avatar_base_path
    if avatar_file.respond_to? :path
      path = File.join(base_path, "avatar.jpg")
      dir = File.dirname(path)
      FileUtils.mkdir_p(dir) unless Dir.exist?(dir)
      # FileUtils.cp(avatar_file.path, path)
      image = MiniMagick::Image.new(avatar_file.path) do |b|
        b.resize '150x150^'
        b.gravity 'center'
        b.crop '150x150+0+0'
      end
      image.format 'jpg'
      image.write path
      update_column(:avatar, true)
    end
  end

  def avatar_destroy
    base_path = avatar_base_path
    FileUtils.rm_r(base_path) if Dir.exist?(base_path)
  end

  def avatar_base_path
    File.join(Rails.public_path, self.class.name.downcase.pluralize, id.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :only_signed_in

  add_flash_types :success, :danger

  helper_method :current_user, :user_signed_in?

  private
  def only_signed_in
    if !user_signed_in?
      redirect_to root_path, danger: "Vous n'êtes pas connecté"
    end
  end

  def only_signed_out
    redirect_to edit_profil_path, danger: "Vous êtes déjà connecté." if user_signed_in?
  end

  def user_signed_in?
    !current_user.nil?
  end

  def current_user
    return nil if !session[:auth] || !session[:auth]['id']
    return user if defined?(user) && user
    user = User.find_by_id(session[:auth]['id'])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :only_signed_in

  def index
    @hello = Rails.env
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

  skip_before_action :only_signed_in

  before_action :only_signed_out


  def new

  end

  def create
    @user = User.find_by_email(user_params[:email])

    if @user
      @user.regenerate_recover_password
      UserMailer.password(@user).deliver_now
      redirect_to new_session_path, success: "Email envoyé avec code de regénération"
    else
      redirect_to new_password_path, danger: "Aucun utilisateur ne correspond"
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user.recover_password != params[:token]
      redirect_to new_password_path, danger: "Token invalide"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.recover_password == user_params[:recover_password]
      @user.attributes = user_params.permit(:password, :password_confirmation)
      if @user.valid?
        @user.recover_password = nil
        @user.save
        session[:auth] = @user.to_session
        redirect_to root_path, success: "Mot de passe maj"
      else
        render :edit, danger: "Probleme"
      end
    else
      redirect_to new_password_path, danger: "Token invalide"
    end
  end

  def user_params
    params.require(:user)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :only_signed_in, only: [:new, :create]

  before_action :only_signed_out, only: [:new, :create]

  def new
  end

  def create
    user_params = params.require(:user)
    user = User.where(username: user_params[:login]).or(User.where(email: user_params[:login])).first
    if user && user.confirmed? && user.authenticate(user_params[:password])
      session[:auth] = user.to_session
      redirect_to edit_profil_path, success: "Connexion réussie"
    else
      redirect_to new_session_path, danger: "Identification incorrecte"
    end
  end

  def destroy
    session.destroy
    redirect_to root_path, success: "Vous êtes déconnecté."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :only_signed_in, only: [:new, :create, :confirm]

  before_action :only_signed_out, only: [:new, :create, :confirm]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.recover_password = nil
    if @user.save
      UserMailer.confirm(@user).deliver_now
      redirect_to root_path, success: "Votre compte a bien été créé, voir les mails."
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    user_params = params.require(:user).permit(:username, :firstname, :lastname, :avatar_file, :email)
    if @user.update(user_params)
      redirect_to edit_profil_path, success: "Compte mis à jour"
    else
      render :edit
    end
  end

  def confirm
    user = User.find(params[:id])
    if user.confirmation_token == params[:token]
      user.update(confirmation_token: nil, confirmed: true)
      session[:auth] = user.to_session
      redirect_to edit_profil_path, success: "Compte confirmé"
    else
      redirect_to root_path, danger: "Désolé le token est erroné."
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= @hello %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5 pe-5">
      <div class="container-fluid">
        <a href="<%= root_path %>" class="navbar-brand">MyAPP</a>
        <ul class="navbar-nav pe-5">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.username %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><%= link_to("Mon profil", edit_profil_path, class: "dropdown-item") %></li>
                <li><%= link_to("Se déconnecter", session_path, data: { method: :delete }, class: "dropdown-item") %></li>
              </ul>
            </li>
          <% else %>
            <li><a href="<%= new_user_path %>" class="nav-link">S'inscrire</a></li>
            <li><a href="<%= new_session_path %>" class="nav-link">Se connecter</a></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= debug session[:auth] %>

    <div class="container">
      <% if flash[:success] %>
        <div class="alert alert-success">
          <%= flash[:success] %>
        </div>
      <% end %>

      <% if flash[:danger] %>
        <div class="alert alert-danger">
          <%= flash[:danger] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="card">
  <div class="card-header">Profil</div>
  <div class="card-body">
    <%= form_for @user, url: profil_path do |f| %>
      <div class="row mb-3">
        <div class="col-md-3">
          <%= image_tag @user.avatar_url if @user.avatar? %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-3">
          <%= f.label :avatar_file, "Avatar", class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= f.file_field :avatar_file, class: "form-control" %>
        </div>
      </div>


      <div class="row mb-3">
        <div class="col-md-3">
          <%= f.label :username, "Nom d'utilisateur", class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= f.text_field :username, class: "form-control" %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-3">
          <%= f.label :email, "Email", class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-3">
          <%= f.label :firstname, "Prénom", class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= f.text_field :firstname, class: "form-control" %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-3">
          <%= f.label :lastname, "Nom", class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= f.text_field :lastname, class: "form-control" %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-9 offset-3">
          <button type="submit" class="btn btn-primary">
            Modifier
          </button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="card">
  <div class="card-header">S'inscrire</div>
  <div class="card-body">
    <%= form_for @user do |f| %>
      <div class="row mb-3">
        <div class="col-md-3">
          <%= f.label :username, "Nom d'utilisateur", class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= f.text_field :username, class: "form-control" %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-3">
          <%= f.label :email, "Email", class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-3">
          <%= f.label :password, "Mot de passe", class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-3">
          <%= f.label :password_confirmation, "Confirmation mot de passe", class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-9 offset-3">
          <button type="submit" class="btn btn-primary">
            S'inscrire
          </button>
        </div>
      </div>
    <% end %>
  </div>
</div>